### ISSUE TITLE
如何介入element-ui

### ISSUE THREAD

**Issue by nigiwen** [x-extends/dom-zindex#1]
# 如何介入element-ui
![image](https://github.com/x-extends/dom-zindex/assets/67454874/0cde8647-6ffd-490a-b998-ea4739791aef)

**Comment by xuliangzhan** [comment]
任何组件库都能使用，需要对应的库引用 dom-zindex 就可以实现跨组件库共享 z-index 了

**Comment by nigiwen** [comment]
已经解决

**Comment by 425824365** [comment]
> 已经解决

请问下如何解决的
